name: Build and Tag New-githuba-action-workflow

on:
  push:
    branches:
      - New-githuba-action-workflow

jobs:
  build-and-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"

      - name: Create or Update New-githuba-action-workflow Branch
        run: |
          if git show-ref --quiet refs/heads/New-githuba-action-workflow; then
            echo "New-githuba-action-workflow branch exists. Checking out..."
              git checkout New-githuba-action-workflow
            else
              echo "Creating New-githuba-action-workflow branch..."
              git checkout -b New-githuba-action-workflow
            fi

      - name: Auto Increment Tag
        run: |
          # Fetch all tags
          git fetch --tags
        
          # Get the latest New-githuba-action-workflow tag
          latest_tag=$(git tag -l "New-githuba-action-workflow-*" --sort=-v:refname | head -n 1)
            
          # If no tag exists, start from New-githuba-action-workflow-1.0.0
          if [[ -z "$latest_tag" ]]; then
            new_tag="New-githuba-action-workflow-1.0.0"
          else
            # Extract numeric version components
          version=$(echo "$latest_tag" | sed 's/New-githuba-action-workflow-//')
            IFS='.' read -r major minor patch <<< "$version"
              
          # Increment patch version
            new_tag="New-githuba-action-workflow-${major}.${minor}.$((patch + 1))"
          fi
        
            echo "New Tag: $new_tag"
            echo "TAG_NAME=$new_tag" >> $GITHUB_ENV
        
      - name: Push New-githuba-action-workflow Branch and Tag
        run: |
          git push origin New-githuba-action-workflow
          git tag $TAG_NAME
          git push origin $TAG_NAME

