name: Publish NuGet Package

on:
  push:
    branches:
      - nuget-build-publish-deploy
    paths:
      - 'WebApplication1/*'
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
          source-url: https://nuget.pkg.github.com/kdahal/index.json

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Solution
        run: dotnet build --configuration Release --no-restore

      - name: Pack NuGet Package
        run: dotnet pack --configuration Release --no-build --output nupkgs

      - name: Push to GitHub Packages
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          dotnet nuget push nupkgs/*.nupkg --source "https://nuget.pkg.github.com/kdahal/index.json" --api-key $NUGET_AUTH_TOKEN --skip-duplicate
